POST http://localhost:8080/orphanages
Content-Type: application/json

{
  "name": "Orfanato ficticio",
  "latitude": -23.292677,
  "longitude": -51.277449,
  "about": "Sore o orfanato ficticio",
  "instructions": "Venha visitar",
  "opening_hours": "Das 8h até 18h",
  "open_on_weekends": true
}

###
