version: '3'

services:
    database:
      container_name: database
      image: mongo:7
      restart: unless-stopped
      ports:
        - "${DB_PORT}:27017"
      environment:
        TZ: "${TIMEZONE}"
        MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
        MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
        MONGO_INITDB_DATABASE: "happy"
      volumes:
        - ./configurations/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        - ~/.volumes/happy/database/mongodb:/data/db